FROM openjdk:slim-buster

WORKDIR /tmp

RUN apt update

# Установка зависимостей для скачивания и сборки python
RUN apt install \
    build-essential \
    zlib1g-dev \
    libncurses5-dev \
    libgdbm-dev \
    libnss3-dev \
    libssl-dev \
    libreadline-dev \
    libffi-dev \
    libsqlite3-dev \
    wget \
    libbz2-dev -y

# Скачивание python 3.10
RUN wget https://www.python.org/ftp/python/3.10.0/Python-3.10.0.tar.xz && \
    tar -xf Python-3.10.0.tar.xz

# Сборка python 3.10
RUN cd Python-3.10.0 && \
    ./configure --enable-optimizations && \
    make && \
    make altinstall

# Создаем ссылку на python3.10 для команды python
RUN update-alternatives --install /usr/bin/python python /usr/local/bin/python3.10 10

# Очистка временных файлов
RUN rm -rf /tmp/*

# Скачивание allure
WORKDIR /allure

RUN wget https://github.com/allure-framework/allure2/releases/download/2.19.0/allure-2.19.0.tgz && \
    tar -xf allure-2.19.0.tgz

ENV ALLURE__ALLURE_PATH=/allure/allure-2.19.0/bin/allure
